### ISSUE TITLE
Reviewing Contract

### ISSUE THREAD

**Issue by ngmachado** [sunnyjaycer/stream-rebounder#3]
Some comments:

- Remove unused imports: https://github.com/sunnyjaycer/stream-rebounder/blob/2247e5049595c698c3492dbed1af57c197a7cd05/contracts/StreamRebounder.sol#L4

_There are more imports not used._

- Can we use the custom errors pattern? 

- Don't think this is necessary, always mirror incoming stream. https://github.com/sunnyjaycer/stream-rebounder/blob/2247e5049595c698c3492dbed1af57c197a7cd05/contracts/StreamRebounder.sol#L25

-  Outside testnets we need to give a key, maybe using the pattern if key is given use it, if not default to this method call. https://github.com/sunnyjaycer/stream-rebounder/blob/2247e5049595c698c3492dbed1af57c197a7cd05/contracts/StreamRebounder.sol#L47

- I think if the user closes receiving stream we should respond by closing incoming stream, and not try to be sticky. https://github.com/sunnyjaycer/stream-rebounder/blob/2247e5049595c698c3492dbed1af57c197a7cd05/contracts/StreamRebounder.sol#L141

- Unneeded assert 
https://github.com/sunnyjaycer/stream-rebounder/blob/2247e5049595c698c3492dbed1af57c197a7cd05/contracts/StreamRebounder.sol#L32

_If Host is address zero, will revert when init CFA Library_

**Comment by joeljesu** [comment]
Addresssed in https://github.com/sunnyjaycer/stream-rebounder/commit/511808e7579deec2f100ad437d02b83ab08feb90

Thanks!
